### ISSUE TITLE
MySQL configuration supported?

### ISSUE THREAD

**Issue by fdemello** [LaKing/ep_hash_auth#6]
Can the MySQL configuration be modified to use hash instead of password with this plugin?

**Comment by LaKing** [comment]
Not sure what you mean, ...

This plugin does not deal with Mysql.

**Comment by fdemello** [comment]
I think the idea behind this plugin is to not expose clear text password in the settings.json file of etherpad. When you configure etherpad for mysql, it requires that you enter DB credentials in the settings file and I was wondering if this plugin covered that use case as well.

**Comment by LaKing** [comment]
No, not really.

This plugin deals with usernames and password's so that any user can set a custom password, and since it can be stored as a hash it is not exposed in plaintext to other users in the configs.

Mysql passwords are for internal application use and can be random strings as no one has to keep it in mind. Not sure if hashing the MySQL password would make sense, and if it would be possible to connect to MySQL directly with a hash.

**Comment by LaKing** [comment]
Closing the issue as it is out of scope.
